name: 'Publish Gatsby Site'
description: 'Publish Gatsby generated site to GitHub Pages using https://www.npmjs.com/package/gh-pages'
branding:
  icon: 'cpu'
  color: 'white'

inputs:
  publishBranch:
    default: 'master'
  token:
    required: true
  name:
    default: 'Zhiyuan Zheng'
  email:
    default: 'me@xmflsct.com'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.publishBranch }}
    - ${{ inputs.token }}
    - ${{ inputs.name }}
    - ${{ inputs.email }}
    - ${{ GITHUB_REPOSITORY }}
    - ${{ GITHUB_SHA }}
