name: "Publish Gatsby Site"
branding:
  icon: "cpu"
  color: "white"

inputs:
  repo:
    required: true
  dev-branch:
    required: true
  publish-branch:
    required: true
  token:
    required: true
  name:
    required: true
  email:
    required: true

on:
  push:
    branches:
      - ${dev-branch}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repository: ${repo}
          ref: ${dev-branch}
          token: ${token}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g gatsby-cli
      - run: gatsby telemetry --disable
      - run: yarn
      - run: gatsby build
      - run: yarn run gh-pages -d public -b ${publish-branch} -u '${name} <${email}>' -r https://${token}@github.com/${repo}.git -m 'Build of ${{ github.sha }}'
